[package]
name = "prog1"
version = "0.1.0"
authors = ["Kimmo Matias Vuori Liikaluoma <vuoriliikaluoma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "prog1"
path = "prog1.rs"
